version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cv_user
      - POSTGRES_PASSWORD=cv_password
      - POSTGRES_DB=cv_db
    volumes:
      - cv_db_data:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - ELASIC_PASSWORD=password
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - 9200:9200
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - 5601:5601
  redis:
    image: redis:6.0.4
    container_name: redis
    restart: always
    ports:
      - 6379:6379

volumes:
 cv_db_data:
