server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'cv_db'
  logging: false

redis:
  host: 'localhost'
  port: 6379

elasticsearch:
  host: 'http://localhost'
  port: 9200

jwt:
  expiresIn: 43200

queue:
  cvReloadDelay: 10000
